name: completion
version: 0.1.1
author: Kevin Moore <github@j832.com>
description: A packaged to add shell command completion to your Dart application
homepage: https://github.com/kevmoo/completion.dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.9.0 <0.11.0'
  bot: '>=0.26.0 <0.27.0'
  logging: '>=0.9.0 <0.10.0'
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  hop: '>=0.28.1+2'
  unittest: '>=0.10.0 <0.11.0'
